files:
  - source: >-
      /modules/matterhorn-admin-ui-ng/src/main/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
    translation: >-
      /modules/matterhorn-admin-ui-ng/src/main/resources/public/org/opencastproject/adminui/languages/lang-%locale_with_underscore%.json
  - source: >-
      /modules/matterhorn-engage-theodul-core/src/main/resources/ui/language/en-US.json
    translation: >-
      /modules/matterhorn-engage-theodul-core/src/main/resources/ui/language/%locale%.json
