site_name: Opencast - Developer Guide
repo_url: https://bitbucket.org/opencast-community/matterhorn/src/develop/docs/guides/developer/docs

# Default theme used is readthedocs
theme: readthedocs

# The directory that contain the source .md files
docs_dir: 'docs'

# The directory to which the site is built using mkdocs
site_dir: 'site'

# This needs to be listed in order to populate the left navigation and the TOC
# Items will appear in this order

pages:
- Home: 'index.md'
- Development Process:
   - Development: 'development-process.md'
   - Reviewing, Merging and Declining Pull Requests: 'reviewing-and-merging.md'
   - Release Manager: 'release-manager.md'
- Development Environment: 'development-environment.md'
- Licenses and Legal Matters: 'license.md'
- Packaging: 'packaging.md'
- Proposal Log: 'proposal-log.md'
- Developer Documentation:
   - Stream Security: 'stream-security-insights.md'
- Infrastructure:
   - Overview: 'infrastructure/index.md'
   - Nexus Maven Repository: 'infrastructure/nexus.md'
- Module specific Development:
   - Admin-UI-NG: 'admin-ui-ng.md'
